### ISSUE TITLE
when is it open？

### ISSUE THREAD

**Issue by wyk0517** [cradleai/rdif#1]
It has been almost 7 months， what are you doing？ You have done experiment and publish paper， why it's so time-consuming?

**Comment by SamMuq** [comment]
Due to an unexpected change in privacy policy regarding the release of clinical text data, our permission to publish the Renal Direct ImmunoFluorescence (RDIF) dataset has been temporarily suspended. We are actively negotiating how we can release the RDIF dataset in compliance with the new privacy restrictions. We sincerely apologize for the delay.
