### ISSUE TITLE
empty repo?

### ISSUE THREAD

**Issue by kaisadadi** [cradleai/rdif#2]
I really hate those who state they will publish code or data, and give an empty repo. Wish you "really good luck" in your academic career!

**Comment by SamMuq** [comment]
Due to an unexpected change in privacy policy regarding the release of clinical text data, our permission to publish the Renal Direct ImmunoFluorescence (RDIF) dataset has been temporarily suspended. We are actively negotiating how we can release the RDIF dataset in compliance with the new privacy restrictions. We sincerely apologize for the delay.

**Comment by kaisadadi** [comment]
The excuse of unexpected change is a wise answer. I also suggest you to retrieve your paper.
